export enum ResultScenario {
  BOTH_INCORRECT,
  BOTH_NOT_ANSWERED,
  P1_QUICKER_CORRECT,
  P2_QUICKER_CORRECT,
  P1_CORRECT_P2_INCORRECT,
  P2_CORRECT_P1_INCORRECT,
  P1_CORRECT_P2_NOT_ANSWERED,
  P2_CORRECT_P1_NOT_ANSWERED,
  P1_INCORRECT_P2_NOT_ANSWERED,
  P2_INCORRECT_P1_NOT_ANSWERED,
}
